export const products = [
  {
    id: 1,
    name: "Bright Bulb",
    description: "Bright, energy-efficient LED bulb with 80% power savings.",
    image: "/ledblb.jpg",
    price: "₹100",
    available: "Available In Watts: 9w | 12w | 15w | 20w | 30w | 40w | 50w",
    order: "Chat and Order",
  },
  {
    id: 2,
    name: "UrbanBeam Streetlight",
    description: "Stylish streetlight with efficient and uniform illumination.",
    image: "/streetlgt.png",
    price: "₹100",
    available: "Available In Watts: 24w | 36w | 50w | 70w | 100w",
    order: "Chat and Order",
  },
  {
    id: 3,
    name: "ShineBright Floodlight",
    description: "Powerful outdoor floodlight for bright and safe surroundings.",
    image: "/floodlgt.jpg",
    price: "₹100",
    available: "Available In Watts: 30w | 50w | 100w | 150w | 200w",
    order: "Chat and Order",
  },
  {
    id: 4,
    name: "LightCube COB",
    description: "Modern lighting solution with sleek design and powerful glow.",
    image: "/cob.png",
    price: "₹100",
    available: "Available In Watts: 3w | 5w | 7w | 12w | 15w | 18w | 22w | 26w | 30w",
    order: "Chat and Order",
  },
  {
    id: 5,
    name: "SkyPanel",
    description: "Soft, diffused light for homes and offices with a modern touch.",
    image: "/panel.jpeg",
    price: "₹100",
    available: "Available In Watts: 3w | 6w | 8w | 12w | 15w | 22w",
    order: "Chat and Order",
  },
  {
    id: 6,
    name: "EcoGlow Tubelight",
    description: "Eco-friendly tubelight combining efficiency and performance.",
    image: "/t5.jpeg",
    price: "₹100",
    available: "Available In Watts: 18w | 20w | 24w | 36w",
    order: "Chat and Order",
  },
];
